# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a706439e628e21dc8dcb9a48c9ccad4dc7a2ef0d26acab85a5447a314b9eb40600004e3bd4c019a3510121856926a707eb2ed621f1195ad81badc308eba0d65d

test:
  secret_key_base: 8e0078bea4b038e26349eebf77417d1fcfd14836250cb4d87ddf14e9179df6909ebd4673aab1d94a3a66b46de623598ff5b92989e11459965aa463c330534ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
